# Generated by Django 4.2.18 on 2025-02-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
    ]
