# Generated by Django 4.2.18 on 2025-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_active_comment_approved_remove_comment_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="post",
            name="field_2",
            field=models.CharField(default="Hello, world!", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="field_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
