# Generated by Django 4.2.18 on 2025-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comment_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="default_name", max_length=100),
        ),
    ]
