# Generated by Django 4.2.18 on 2025-02-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_comment_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
