# Generated by Django 4.2.18 on 2025-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_comment_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=200)),
                ("event_date", models.DateTimeField()),
            ],
        ),
    ]
